export const messages = {
  error: "Error!",
  cantFindAnyThing: "bai gi la vay???",
  joinVoiceChannel: "vào chỗ nào nói để chụy nhảy vào nào!",
  failToJoinVoiceChannel: "Failed to join voice channel!",
  failToPlay: "k thích bật đọ!!",
  addedToQueue: "Added to queue by",
  author: "Author",
  length: "Length",
  type: "Type",
  platform: "Platform",
  noSongsInQueue: "No songs in queue!",
  skippedSong: "Skipped song!",
  notPlaying: "Not playing!",
  alreadyPaused: "Already paused!",
  paused: "Paused!",
  resumed: "Resumed!",
  alreadyPlaying: "Already playing!",
  leaved: "tạm biệt các chick chụy đi đây!!!!",
  nothing: "Nothing",
  yourQueue: "Your queue",
  invalidPosition: "Invalid position!",
  jumpedTo: "đến bài",
  removed: "Removed",
  help: "Help",
  ping: "Ping",
  owner: "người tạo",
  description: "chi tiết",
  addTaskBy: "thêm mới công việc từ",
  userTarget: "người được giao",
  listTask:"danh sách các công việc"
};
