export const messages = {
  error: "Error!",
  cantFindAnyThing: "bai gi la vay???",
  joinVoiceChannel: "Join a voice channel and try again!",
  failToJoinVoiceChannel: "Failed to join voice channel!",
  failToPlay: "i do not like play for you!!",
  addedToQueue: "Added to queue by",
  author: "Author",
  length: "Length",
  type: "Type",
  platform: "Platform",
  noSongsInQueue: "No songs in queue!",
  skippedSong: "Skipped song!",
  notPlaying: "Not playing!",
  alreadyPaused: "Already paused!",
  paused: "Paused!",
  resumed: "Resumed!",
  alreadyPlaying: "Already playing!",
  leaved: "why did you kick me",
  nothing: "Nothing",
  yourQueue: "Your queue",
  invalidPosition: "Invalid position!",
  jumpedTo: "Jumped to",
  removed: "Removed",
  help: "Help",
  ping: "Ping",
};
